---
title: "Babynames"
author: "Jack Haight"
date: '2022-06-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(ggplot2)
library(babynames)
library(ggthemes)
library(knitr)
library(pander)


```



## Getting to know `babynames`


Names of the columns: `r pander(names( babynames ))`. 
Here are the first few rows in the dataset:

```{r}
# A look at the first few rows.
kable(head(babynames))
```

## Let's count and plot some stuff


```{r}
# count the number of males and females born (and registered!) in 1880 ;
# just look at the result instead of saving as a data.frame
babynames %>% 
  filter( year == 1880 ) %>%
  group_by(sex) %>%
  tally() 

# tally up the number of baby names by year and by sex, 
# save the results in a data.frame called name_counts
name_counts <- babynames %>%
  group_by(year, sex) %>%
  tally() 


# look at the first few rows of name_counts
kable(head( name_counts ))
```


## Plots

```{r, names_over_time, fig_cap = "A caption"}
# plot some counts ----

ggplot( ) +
  geom_line( data = name_counts, 
             aes( x=year, y=n, color=sex) )  +
  labs( title = "Unique names over time",
        subtitle = "By sex",
        caption = "DataLab 2022")

ggplot( data = name_counts, 
        aes( x = year, 
             y = n )) +
  geom_line() +
  facet_wrap( ~sex, ncol=1 ) +
  labs( x = "Year",
        y = "Number of names",
        title = "Unique names over time",
        subtitle = "By sex", 
        caption = "DataLab 2022")
```











